localhost:1521/XEPDB1

-- Создание схемы
CREATE USER my_schema IDENTIFIED BY my_password;
GRANT CONNECT, RESOURCE TO my_schema;


-- Вход в созданную схему
ALTER SESSION SET CURRENT_SCHEMA = my_schema

-- Создание таблиц
CREATE TABLE employees ( 
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    hire_date DATE DEFAULT SYSDATE,
    salary NUMBER(8,2)
);

-- Вставка данных в таблицу employees
INSERT INTO employees (first_name, last_name, salary) VALUES ('Dima', 'Kunitsin', 85000);
INSERT INTO employees (first_name, last_name, salary) VALUES ('Nastya', 'Pavlugina', 55000);
INSERT INTO employees (first_name, last_name, salary) VALUES ('Vanya', 'Stepanov', 400000);
INSERT INTO employees (first_name, last_name, salary) VALUES ('Bob', 'Brown', 45000);

-- Потверждение транзакции
COMMIT;

-- Запрос для получения всех сотрудников
SELECT * FROM employees

-- Запрос для получения сотрудников с запралатой выше 50к
SELECT * FROM employees WHERE salary > 50000;

-- Запрос для подсчета колличества сотрудников
SELECT COUNT(*) AS total_employees FROM employees;

-- Запрос для получения средней запралаты сотрудников
SELECT AVG(salary) AS average_salary FROM employees;

-- Запрос для получения сотрудников, нанятых после определнной даты
SELECT * FROM employees WHERE hire_date > TO_DATE('2023-01-01', 'YYYY-MM-DD');

-- Удаление таблицы 
DROP TABLE employees

